services:
  api:
    build: .
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: .
          target: /app
